### ISSUE TITLE
Research (Information Gathering)

### ISSUE THREAD

**Issue by ibportugal** [ibportugal/mms142-groupk-2023.github.io#2]

**Comment by CatPL8** [comment]
Working on Introduction - Definition

**Comment by littleblackstars** [comment]
Currently researching on the functionality.

**Comment by CatPL8** [comment]
Will add my part (Introduction - Definition) Monday night, Dec. 11.

**Comment by m1rabee** [comment]
Working on Example 1 #16

**Comment by KalmPinpin** [comment]
Working on and Researching on  Disruptive Issues (Topics that I am focusing on researching are AI and Cloud Services)

**Comment by ibportugal** [comment]
Status: Done
