### ISSUE TITLE
Introduction (Coding)

### ISSUE THREAD

**Issue by ibportugal** [ibportugal/mms142-groupk-2023.github.io#3]
Just trying out Github's issues and projects.

**Comment by CatPL8** [comment]
@popinobien moved us here

**Comment by CatPL8** [comment]
@popinobien pls use the text that's on README or here: https://docs.google.com/document/d/1qS5K19xR602_wiZVBCMtyYx8eMPw8ZGVLyOGfaFxOxM/edit?usp=drive_link

thanks!

**Comment by popinobien** [comment]
got it, Cat!

**Comment by popinobien** [comment]
contents of the introduction have been entered to index. html
