### ISSUE TITLE
Introduction (Content)

### ISSUE THREAD

**Issue by ibportugal** [ibportugal/mms142-groupk-2023.github.io#4]

**Comment by CatPL8** [comment]
Will be working on Introduction - Definition

**Comment by popinobien** [comment]
Hi Cat! Will work on the webpage counterpart of your intro.

**Comment by CatPL8** [comment]
Will add my part (Introduction - Definition) Monday night, Dec. 11.

**Comment by popinobien** [comment]
Hi Cat. Since the suggestion is to create a webpage of your assigned content, I unassigned to myself  the webpage creation of the introduction. If you need help, let me know :)

**Comment by CatPL8** [comment]
[MMS 142_Low-Code and No-Code (LCNC) Technologies_Intro-Definition_cpalileo.docx](https://github.com/ibportugal/mms142-groupk-2023.github.io/files/13636286/MMS.142_Low-Code.and.No-Code.LCNC.Technologies_Intro-Definition_cpalileo.docx)

**Comment by CatPL8** [comment]
Alternatively, this is a link to the same doc: https://docs.google.com/document/d/1qS5K19xR602_wiZVBCMtyYx8eMPw8ZGVLyOGfaFxOxM/edit?usp=sharing

Important notes: 

1. Take a look at my last paragraph and let me know if you'd like to include our stance on the tech as disruptor or you want to leave it for the conclusion. Similarly - what is our stance? How does it disrupt? Let me know so I can tweak the info. Our project guidelines says:  "Your report should explain what disruptive technologies are in the context of your chosen topic.

You must explain why your chosen technology can be considered disruptive and illustrate what the current situation is and show how your chosen technology disrupts that. You may embed media and write different sections in your report as you see fit."

2. References are already in APA, will add it to the correct space tomorrow.

3. Will also start coding tomorrow. It's not my strongest suit, so will most likely ask for help and take you up on your offer @popinobien  :)

**Comment by popinobien** [comment]
Hi Cat! I tried working on the coding part but noticed there is already an introduction [here](https://ibportugal.github.io/mms142-groupk-2023.github.io/#intro). @ibportugal, please confirm if I can overwrite this. Too many commits on our index.html already that I couldn't confirm if you put the contents. Thanks!

**Comment by ibportugal** [comment]
Hi @popinobien 

Yeah, you can overwrite the current introduction in index.html

This was only my tentative introduction and I am not really satisfied with it so please change/edit the contents as you see fit

**Comment by littleblackstars** [comment]
Hello, don't forget to encode it first on README.md so that everyone can have a basis on the content once we transfer everything to the website, which is also subject for copyreading later. Thank you!

**Comment by CatPL8** [comment]
thanks for the help @popinobien ! 
noted @littleblackstars , added my content and references to README.me. thanks!

**Comment by littleblackstars** [comment]
Hello, I already saw the encoded article on README file. However, kindly check this comment I posted regarding your reference. https://github.com/ibportugal/mms142-groupk-2023.github.io/commit/b9ea351b891e800a741fff6f715f2f9df3cafad4#r134774129
