### ISSUE TITLE
Proofread (Content)

### ISSUE THREAD

**Issue by ibportugal** [ibportugal/mms142-groupk-2023.github.io#9]

**Comment by popinobien** [comment]
Hi @littleblackstars. I did some proofreading of the functionality piece and attached are my suggested revisions. Please take a look and let me know if you are okay with this.
[functionality - proofread.docx](https://github.com/ibportugal/mms142-groupk-2023.github.io/files/13681145/functionality.-.proofread.docx)

**Comment by littleblackstars** [comment]
Hi @popinobien, most of the suggestions/corrections are fine, while I did not apply some of it due to its technicality and it somehow altered the definition given its case. Regards, thank you for this!

**Comment by popinobien** [comment]
You're welcome!

**Comment by ibportugal** [comment]
Status: Done
